site_name: Mcblend

nav:
    - Home:
      - About: index.md
      - Installation: installation

    - User manual:
      - Basics: user_manual/basics
      - Conversion rules: user_manual/conversion_rules
      - Custom properties - panel: user_manual/custom_properties
      - Export bedrock model - panel: user_manual/export_model
      - Export bedrock animation - panel: user_manual/export_animation
      - Set bedrock UVs - panel: user_manual/set_uvs
      - Parenting mcbones: user_manual/parenting
      - Glossary: user_manual/glossary


theme: 
    name: readthedocs
    titles_only: true