site_name: Mcblend

nav:
    - Overview: index.md
    - Limitations: limitations/index.md
    - Conversion rules: conversion_rules/index.md
    - GUI changes: gui_changes/index.md
    - Basic Operators: basic_operators/index.md
    - Animating effects: animating_effects/index.md
    - UV-groups: uv_groups/index.md
    - Texture customization (advanced): texture_customization/index.md
    - Tips and tricks: tips_and_tricks/index.md

theme:
    name: readthedocs
    favicon: img/favicon.ico
    titles_only: false

markdown_extensions:
    - admonition
