site_name: Mcblend

nav:
    - Home:
      - About: index.md
      - Installation: installation.md

    - User manual:
      - user_manual/basics.md
      - user_manual/conversion_rules.md
      - user_manual/custom_properties.md
      - user_manual/export_model.md
      - user_manual/export_animation.md
      - user_manual/set_uvs.md
      - user_manual/parenting.md
      - user_manual/glossary.md


theme: 
    name: readthedocs
    titles_only: true